### ISSUE TITLE
Adicionar mais opções e corrigir erro

### ISSUE THREAD

**Issue by ianfelix** [ricardoemerson/create-react-tsx-component#3]
Uma sugestão e erro.

Erro:
Ao adicionar um componente com o file js e o style em css ele cria um styles.js ao invés do .css

![image](https://user-images.githubusercontent.com/62842327/92417788-69952280-f13a-11ea-9f2d-0e0f42a540a0.png)

Sugestão:
Adicionar mais uma opção para css modules

![image](https://user-images.githubusercontent.com/62842327/92417850-d4465e00-f13a-11ea-9b4f-b56cccdd8623.png)

Ficaria assim com o file js e o modules adicionado:

![image](https://user-images.githubusercontent.com/62842327/92417877-01930c00-f13b-11ea-80f0-85eb887bcb5a.png)

**Comment by ricardoemerson** [comment]
Olá @ianfelix, muito obrigado pelo seu feedback e informo que já fiz a correção do erro. Quanto a questão do css modules, depois darei uma olhada com calma e avalairei a viabilidade desta modificação.

Abs.

**Comment by ricardoemerson** [comment]
@ianfelix inclui na versão 1.5 o suporte para CSS Module.
