### ISSUE TITLE
How to change componentsFileNames

### ISSUE THREAD

**Issue by maicolsantos** [ricardoemerson/create-react-tsx-component#5]
Is it possible to make this change?

**Comment by ricardoemerson** [comment]
Today no, but I am thinking in add a new menu item or option in settings to allow create a named component. 

In this case, when a component it's created, only a file will be created with the name that user specified in the input box and the folder that contains the component will not be created.

**Comment by ricardoemerson** [comment]
@maicolsantos I include in version 1.5.0 the option for create named components.
