### ISSUE TITLE
Adicionar uma interface padrão para componentes escritos em funções.

### ISSUE THREAD

**Issue by douglasgomes98** [ricardoemerson/create-react-tsx-component#7]
Quando um component for escrito em Typescript, ao invés de deixar ele igual ao feito em JavaScript, fazer essas alterações. Com isso já poupa o tempo de sempre criar uma interface.

Web Atual:
![header1](https://user-images.githubusercontent.com/47008462/108575594-2b0eb100-72f1-11eb-8d97-ad9b55723dde.png)
 
Web Atualizado:
![header2](https://user-images.githubusercontent.com/47008462/108575618-3b269080-72f1-11eb-8492-2e13398233c3.png)

React Native Atual:
![Footer](https://user-images.githubusercontent.com/47008462/108575647-4e396080-72f1-11eb-8c75-d310fb3b8cc2.png)

React Native Atualizado:
![Footer2](https://user-images.githubusercontent.com/47008462/108576120-c5bbbf80-72f2-11eb-895d-8f51705f56c8.png)

**Comment by ricardoemerson** [comment]
Fiz uma nova atualização para a extensão hoje e nesta atualização está contemplada a sua solicitação, com uma diferença de que as props estão desistruturadas.

```
import { ReactNode } from 'react';

import { Container } from './styles';

interface CardProps {
  children: ReactNode;
}

function Card({ children }: CardProps) {
  return (
    <Container>
      <h1>Card</h1>
      {children}
    </Container>
  );
};

export default Card;
```
